services:
  backend:
    build:
      context: ./Back_Electromanía
      dockerfile: Dockerfile
      target: development
    container_name: electromania-backend-dev
    image: electromania-backend:dev
    env_file:
      - .dev.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./Back_Electromanía/src:/usr/src/app/src
      - ./Back_Electromanía/prisma:/usr/src/app/prisma
      - ./Back_Electromanía/nest-cli.json:/usr/src/app/nest-cli.json
      - ./Back_Electromanía/tsconfig.json:/usr/src/app/tsconfig.json
      - ./Back_Electromanía/tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - uploads_data:/usr/src/app/uploads
      - /usr/src/app/node_modules

    ports:
      - "3000:3000"

    command: sh -c "pnpm prisma migrate dev && pnpm start:dev"

  frontend:
    build:
      context: ./electromania-frontend
      dockerfile: Dockerfile
      target: development
    container_name: electromania-frontend-dev
    image: electromania-frontend:dev
    volumes:
      - ./electromania-frontend:/usr/src/app
      - angular_cache:/usr/src/app/.angular/cache
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "4200:4200"

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    env_file: .dev.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg_data:
  uploads_data:
  angular_cache: