name: Construct-CI

on:
  push:
    branches:
      - main
      - feat/backend/*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    environment: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        run: docker compose version

      - name: Create .env file
        run: |
            cat <<EOF > .dev.env
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_URL=postgresql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT }}/${{ secrets.DATABASE_NAME }}?schema=public
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}
            BCRYPT_SALT_ROUNDS=${{ secrets.BCRYPT_SALT_ROUNDS }}
            PORT=${{ secrets.PORT }}
            API_DOMAIN=${{ secrets.API_DOMAIN }}
            EOF
      - name: Build and start containers
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
