name: Construct-CI

on:
  push:
    branches:
      - main
      - feat/backend/*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    environment: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        run: docker compose version

      - name: Create .env file
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
          echo "BCRYPT_SALT_ROUNDS=${{ secrets.BCRYPT_SALT_ROUNDS }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for DB
        run: sleep 15

      - name: Run Prisma migrations
        working-directory: ./Back_Electroman√≠a
        run: pnpm prisma migrate deploy

      - name: Run Tests
        run: docker exec electromania-backend pnpm run test

      - name: Stop containers
        if: always()
        run: docker compose down -v
